### PR TITLE
98 user authorization

### PR DESCRIPTION
**Pull request by HaleyBoles**
**Note: Needs some good testing. I tried it out with all current roles, but a second & third set of eyes will be good. Can uncomment section in user settings to see current perms/access/restrictions**

- Added returned user authentication to useUserAuth hook in useRequireAuth file
- Moved useTenantAuth into useRequireAuth
- Added dashboard redirects in the hooks for when you get somewhere you shouldn't be 
     - required perm passed in use[x]Auth moduleAuth with optional authType for read/write
- Added `<Show>` component 
- Implemented `<Show>` component for module and user auth
- Updated module/user calls to use hooks
- Updated Alt Slash options object format to check perms
- Updated App Layout links to check perms
- Updated all pages with links/redirects to show/hide (or do something/nothing) based on perms
- Updated server settings to only show "update reports" and "sync" if you don't have scale settings perm
- Updated truck add/edit to not show if you can't read trucks
     - Don't show truck details section if you can't write trucks
     - Don't show in-yard section if you can't write loader
     - Don't show inactive trucks if you can't write trucks
     - Can't add trucks if you can't write trucks
- Added conditional page subtitles based on perms

**This one can also wait to merge until Steph's GQL changes are complete**

### CODE REVIEW

**Comment by ericwilhite** [comment]
@HaleyBoles here be conflicts

**Review by ericwilhite — COMMENTED** [review]
Testing and it all seems to work...

@sspoon865 this is big enough it probably warrants all eyes on it. I will wait to merge until you can look over it.

**Comment by sspoon865** [comment]
Not bad not bad!

**Comment by HaleyBoles** [comment]
> @HaleyBoles here be conflicts

@ericwilhite @sspoon865 
Resolved conflicts and merged main

**Comment by ericwilhite** [comment]
I think I'm going to merge this and tell our support guys lets test the heck out of it

**Comment by ericwilhite** [comment]
Is this UI compatible with older server versions you think? > .60?
Thinking about the other installs we have out in wild

**Comment by HaleyBoles** [comment]
> Is this UI compatible with older server versions you think? > .60? Thinking about the other installs we have out in wild

Hmmmm some of the properties on the user query did not exist as of like.. a couple versions ago so I would say no

**Comment by ericwilhite** [comment]
@HaleyBoles do you know min version num?

**Comment by HaleyBoles** [comment]
> @HaleyBoles do you know min version num?

No idea. I can downgrade to v 0.1.60 and test it out

**Comment by HaleyBoles** [comment]
@ericwilhite All is good on v 0.1.60

**Pull request merged**
