### PR TITLE
36 truck add edit screen accept scale weight for tare entry

### PR DESCRIPTION
**Pull request by HaleyBoles**
still wont build from prettier removing my typing. >:(

### CODE REVIEW

**Comment by ericwilhite** [comment]
@HaleyBoles did you figure out prettier issue? Just saw notification that it builds now.

**Comment by ericwilhite** [comment]
Not sure where the error is coming from but getting this when I try to select a weight during truck edit:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons
```

Also I'm assuming it's a known thing that there are 2 tare entry fields instead of one. Cleaner to do something like the override button on ticketing screen.

**Review by ericwilhite — APPROVED** [review]
I don't mind the idea of having the weights drop down like that. 

But it is odd as a user that I can't use the arrow keys to select one. Since it's a number input field it just goes +/- 1 when you try to arrow up/down.

Also, if you backspace and clear the input field you get "Error: NaN - cannot parse to integer" because it's trying to parse null/undefined into an int.

Going to push this one through but would like to solve both those things.

**Comment by ericwilhite** [comment]
Since the weight is normally a large number I find it easier to look at when formatted as a string anyways...

Here's an example of formatting it with commas and then stripping the commas back out again from the ticketing (lane) screen

```jsx
		<input
			ref={weightInputRef}
			placeholder="0"
			type="text"
			className="w-[120px] rounded border-0 bg-white px-1 py-0 text-center text-lg font-bold text-red-500 shadow outline-0 ring-0"
			value={props.value?.toLocaleString() ?? ""}
			onChange={(e) => {
				props.onChange(Number(e.target.value.split(",").join("")));
			}}
		/>
```

**Comment by HaleyBoles** [comment]
> I don't mind the idea of having the weights drop down like that.
> 
> But it is odd as a user that I can't use the arrow keys to select one. Since it's a number input field it just goes +/- 1 when you try to arrow up/down.
> 
> Also, if you backspace and clear the input field you get "Error: NaN - cannot parse to integer" because it's trying to parse null/undefined into an int.
> 
> Going to push this one through but would like to solve both those things.

I can look at changing the input field back to string, just set it to Number so you can't enter any non-numbers into the field by default. Will pull a new branch for fixes

**Pull request merged**
