### PR TITLE
128 standardize buttons grids headers etc

### PR DESCRIPTION
**Pull request by HaleyBoles**
**Buttons**
- added "designation" to Button component
  - designation auto styles button, auto types button, sometime auto-sets icon
  - added ButtonExamples and added it to dev mode of userSettings route (can remove later)
- Updated most buttons to have a designation for standardization
- refined button styles 
   - Blue and Slate more unique
   - Red less red
   - Teal normal more readable

**Doc Title**
- Updated DocumentTitle to append "Fast-Weigh - " to match Order screen and so all screens use same format
- added document title to settings screens

**Headers**
- updated all page headers to use same formatting

**Customers**
- Added flexes to Customer grid

**Lanes**
- Lane Route did the prettier formatting thing
- Moved Repeat Last Load to front of truck action buttons for consistency of colors

**Pop-ups**
- Start standardizing pop-up formatting/button location (new issue for component for this)

**Requests**
- Request filters: put region location above customer order

**Trucks**
- Trucks grid: fixed assignedOrderProduct
- added some flexes

**Other**
- Added a little pulse animation to Server Update Available

### CODE REVIEW

**Comment by HaleyBoles** [comment]
Standardization for review. 

Not sure why its not building? It does in VS Code??

**Comment by ericwilhite** [comment]
I think there's some good ideas in here but I'm not super happy with all of the color variations on the screen.

The truck add/edit and lane routes in particular are button heavy and all of the variation in color is a bit much.

I made some tweaks and changed some designations to try to calm it down a bit but I feel like we are missing something from a component design wise.

My late night brain is telling me that variant and designation could really be the same thing. Let's chat about it tomorrow AM.

(also yeah IDK about the whole not building thing... builds on mine as well)

**Comment by ericwilhite** [comment]
RE failed build:
Apparently Node v20.6 broke a bunch of stuff. I see other people complaining as well. So... safe to ignore for now. if they don't fix it in next day or 2 I will remove the 20.x build step but keep 18.x

**Comment by HaleyBoles** [comment]
@sspoon865 @ericwilhite ready for review v2: now with more blue

**Review by sspoon865 — APPROVED** [review]
Checked on a call, looks great!!

**Pull request merged**
