### PR TITLE
160 truck screen - fix use weight from scale & other cleanup

### PR DESCRIPTION
**Pull request by HaleyBoles**
UDF 
- Made disabled optional
- Added render shadow

Queries
- Added prefilter to useHaulers

TrucksAddEdit
- swapped scale usage from store to new useScales and fixed everything to work with new version
- swapped notifications from store to toast
- condensed tareWeight and displayTareWeight to one field
- swapped UDFs to use component
- changed exit button to nav to Trucks instead of going back
- Fixed typing errors by removing type assertions and swapping to key-based
- Added queries when needed where typing was replaced with keys
- Condensed all queries to filter off of one main query per type (IE trucksQuery and initialTruckQuery now both use results from single trucksQuery)
- Cleaned up styling and formatting

Note: the useOrders and useOrderProducts queries are pretty slow on refresh/initial load on my end. Not sure why? May need to investigate further later on

### CODE REVIEW

**Comment by ericwilhite** [comment]
useOrders idk
But useOrderProducts I could make the argument that if not passing in a an order or orderproduct key then we shouldn't be returning anything at all. Right now it's returning back all order products in the db when you first visit the page (and probably ticketing too). Maybe that query running concurrently with all of the other queries is slowing down the useOrders

**Comment by ericwilhite** [comment]
^ Not sure if that would break anything or not. If anywhere is expecting to get the full list of unfiltered order products...

**Comment by HaleyBoles** [comment]
> useOrders idk But useOrderProducts I could make the argument that if not passing in an order or orderproduct key then we shouldn't be returning anything at all. Right now it's returning back all order products in the db when you first visit the page (and probably ticketing too). Maybe that query running concurrently with all of the other queries is slowing down the useOrders

Oh very true. You can't select an OrderProduct without an Order, so I think it should be fine to pre-filter this. Let me try that out and push a new version before this is OKed

**Comment by ericwilhite** [comment]
Also I think the scale selection under the tare input should be more clear they are selectable items. They kinda just look like an info list. Not clear you should click one to select.

**Comment by HaleyBoles** [comment]
> Also I think the scale selection under the tare input should be more clear they are selectable items. They kinda just look like an info list. Not clear you should click one to select.

@ericwilhite Trying to make this more clear. Wanted to see if this helps?

None selected, hover over weight section:
image

None selected, hover over a scale: 
image

Scale selected (set tareWeight and serialPort match a scale in the list), hover over weight section: 
image

Scale selected, hover over another scale: 
image

**Comment by ericwilhite** [comment]
Definitely does help

I think that's good for now. 

Eventually I think we should style it more like a select component that sees the dropdown pop over instead of expanding the box and displaying inline. Something like the headlessUI combobox

**Comment by ericwilhite** [comment]
If you aren't going to load all orders on pageload then need to disable that until customer selection

**Comment by ericwilhite** [comment]
But it does seem strange / inconsistent to not be able to jump straight to orders

**Comment by HaleyBoles** [comment]
Change mentioned above was to the actual graphQL to get Orders without the OrderProducts object and vice versa since the queries are totally separate. This page does not need OrderProducts in the Orders query and vice versa, and that was what was making it take forever to load.

**Review by ericwilhite — APPROVED** [review]

**Pull request merged**
